#!/bin/bash

# create connector
curl -i -X POST -H Accept:application/json -H Content-Type:application/json -d @connect-config.json http://localhost:8083/connectors/

# tail the output
ruby dump-avro-encoded-topic.rb products | bat -l json --paging=never --style=plain
