#!/bin/bash

# create connector
curl -i -X POST -H Accept:application/json -H Content-Type:application/json -d @connect-config.json http://localhost:8083/connectors/

# tail the output
ruby example.rb | bat -l json --paging=never
